## Lab 3 - Video Game Reviews

In [2]:
from math import nan

In [3]:
import pandas as pd

### Import Data

In [4]:
df = pd.read_csv('imdb-videogames.csv')

In [5]:
df.head()

,Unnamed: 0,name,url,year,certificate,rating,votes,plot summary,Action,Adventure,Comedy,Crime,Family,Fantasy,Mystery,Sci-Fi,Thriller
0,0,Spider-Man,https://www.imdb.com/title/tt5807780/?ref_=adv...,2018.0,T,9.2,"20,759","When a new villain threatens New York City, Pe...",True,True,False,False,False,True,False,False,False
1,1,Red Dead Redemption II,https://www.imdb.com/title/tt6161168/?ref_=adv...,2018.0,M,9.7,"35,703",Amidst the decline of the Wild West at the tur...,True,True,False,True,False,False,False,False,False
2,2,Grand Theft Auto V,https://www.imdb.com/title/tt2103188/?ref_=adv...,2013.0,M,9.5,"59,986",Three very different criminals team up for a s...,True,False,False,True,False,False,False,False,False
3,3,God of War,https://www.imdb.com/title/tt5838588/?ref_=adv...,2018.0,M,9.6,"26,118","After wiping out the gods of Mount Olympus, Kr...",True,True,False,False,False,False,False,False,False
4,4,Uncharted 4: A Thief's End,https://www.imdb.com/title/tt3334704/?ref_=adv...,2016.0,T,9.5,"28,722",Thrown back into the dangerous underworld he'd...,True,True,False,False,False,False,False,False,False

In [6]:
df.shape

(20805, 17)

In [7]:
df.info

<bound method DataFrame.info of        Unnamed: 0                                 name  \
0               0                           Spider-Man
1               1               Red Dead Redemption II
2               2                   Grand Theft Auto V
3               3                           God of War
4               4           Uncharted 4: A Thief's End
...           ...                                  ...
20800       20798  Enjoy Your Power, Enjoy Your Choice
20801       20799                           RedSun2020
20802       20800                              Shutter
20803       20801                    The Music Machine
20804       20802                              Cryptic

                                                     url    year certificate  \
0      https://www.imdb.com/title/tt5807780/?ref_=adv...  2018.0           T
1      https://www.imdb.com/title/tt6161168/?ref_=adv...  2018.0           M
2      https://www.imdb.com/title/tt2103188/?ref_=adv...  2013.0           M
3      https://www.imdb.com/title/tt5838588/?ref_=adv...  2018.0           M
4      https://www.imdb.com/title/tt3334704/?ref_=adv...  2016.0           T
...                                                  ...     ...         ...
20800  https://www.imdb.com/title/tt3845606/?ref_=adv...  2014.0         NaN
20801  https://www.imdb.com/title/tt0790739/?ref_=adv...  2004.0         NaN
20802  https://www.imdb.com/title/tt5119948/?ref_=adv...  2015.0         NaN
20803  https://www.imdb.com/title/tt5142082/?ref_=adv...  2015.0         NaN
20804  https://www.imdb.com/title/tt10964974/?ref_=ad...  2020.0         NaN

      rating   votes                                       plot summary  \
0        9.2  20,759  When a new villain threatens New York City, Pe...
1        9.7  35,703  Amidst the decline of the Wild West at the tur...
2        9.5  59,986  Three very different criminals team up for a s...
3        9.6  26,118  After wiping out the gods of Mount Olympus, Kr...
4        9.5  28,722  Thrown back into the dangerous underworld he'd...
...      ...     ...                                                ...
20800    NaN     NaN                                         Add a Plot
20801    NaN     NaN  Joseph gets kidnapped and it's the player's jo...
20802    NaN     NaN  A tech support man who uses a drone to investi...
20803    NaN     NaN  A young teenage girl and the ghost of a dead m...
20804    NaN     NaN  Kidnapped by an insane man and dragged into a ...

       Action  Adventure  Comedy  Crime  Family  Fantasy  Mystery  Sci-Fi  \
0        True       True   False  False   False     True    False   False
1        True       True   False   True   False    False    False   False
2        True      False   False   True   False    False    False   False
3        True       True   False  False   False    False    False   False
4        True       True   False  False   False    False    False   False
...       ...        ...     ...    ...     ...      ...      ...     ...
20800   False      False   False  False   False    False    False   False
20801   False      False   False  False   False    False    False   False
20802   False      False   False  False   False    False    False   False
20803   False      False   False  False   False    False    False   False
20804   False      False   False  False   False    False    False   False

       Thriller
0         False
1         False
2         False
3         False
4         False
...         ...
20800      True
20801      True
20802      True
20803      True
20804      True

[20805 rows x 17 columns]>

In [8]:
df.certificate.value_counts()

T            2474
E            2006
M            1820
E10+          814
Unrated       241
K-A           229
Not Rated     184
AO             32
GA             26
EC             25
CE             13
12              9
PG-13           7
MA-13           7
Approved        4
G               4
MA-17           3
PG              3
TV-MA           2
Passed          1
TV-14           1
Name: certificate, dtype: int64

In [9]:
df.columns

Index(['Unnamed: 0', 'name', 'url', 'year', 'certificate', 'rating', 'votes',
       'plot summary', 'Action', 'Adventure', 'Comedy', 'Crime', 'Family',
       'Fantasy', 'Mystery', 'Sci-Fi', 'Thriller'],
      dtype='object')

### Clean Data

Clean and Fix Rating

In [10]:
df.rating.replace("*9.0", "9.0", inplace=True)
df.rating = pd.to_numeric(df.rating)
df.rating.mean

<bound method NDFrame._add_numeric_operations.<locals>.mean of 0        9.2
1        9.7
2        9.5
3        9.6
4        9.5
        ...
20800    NaN
20801    NaN
20802    NaN
20803    NaN
20804    NaN
Name: rating, Length: 20805, dtype: float64>

Clean and Fix Votes

In [11]:
df.votes = df.votes.str.replace(',','')
df.votes = pd.to_numeric(df.votes)
df.votes.mean()

630.9875883468368

Clean and fix Sci-fi name and plot summary name

In [12]:
df.columns = ['Unnamed: 0', 'name', 'url', 'year', 'certificate', 'rating', 'votes',
       'plot_summary', 'Action', 'Adventure', 'Comedy', 'Crime', 'Family',
       'Fantasy', 'Mystery', 'Sci_Fi', 'Thriller']

#### Questions

#### 1. What is the average rating for Action games?

In [13]:
dar = df[(df.Action)].rating.mean()
dar

7.069257468699611

#### 2. What is the average rating of games after 2010? What is the average rating of games before (and including) 2010?

After 2010

In [14]:
mask = df.year > 2010
mask
df[mask].rating.mean()

7.119838056680145

Before and including 2010

In [15]:
mask = df.year <= 2010
mask
df[mask].rating.mean()

7.006822480410717

#### 3. What games include "Fallout" in their title?

In [16]:
games = df[df.name.str.contains("Fallout")]
games

,Unnamed: 0,name,url,year,certificate,rating,votes,plot_summary,Action,Adventure,Comedy,Crime,Family,Fantasy,Mystery,Sci_Fi,Thriller
29,29,Fallout: New Vegas,https://www.imdb.com/title/tt1706601/?ref_=adv...,2010.0,M,8.9,12296.0,"After surviving a bullet to the head, Courier ...",True,True,False,False,False,False,False,True,False
37,37,Fallout 4,https://www.imdb.com/title/tt4741306/?ref_=adv...,2015.0,M,8.6,12790.0,"In the post-apocalyptic Boston, Massachusetts ...",True,True,False,False,False,False,False,True,False
115,115,Fallout 3,https://www.imdb.com/title/tt1073664/?ref_=adv...,2008.0,M,9.1,18904.0,"Centuries following nuclear war, a teen leaves...",True,True,False,False,False,False,False,True,False
207,207,Fallout 76,https://www.imdb.com/title/tt8495446/?ref_=adv...,2018.0,M,4.0,1756.0,"Twenty-five years after the bombs fall, you an...",True,True,False,False,False,False,False,True,False
340,340,Fallout: A Post-Nuclear Role-Playing Game,https://www.imdb.com/title/tt0134648/?ref_=adv...,1997.0,M,9.2,3772.0,After being sent by the overseer of his vault ...,True,True,False,False,False,False,False,True,False
437,437,Fallout 2: A Post-Nuclear Role-Playing Game,https://www.imdb.com/title/tt0183066/?ref_=adv...,1998.0,M,9.4,3861.0,"In a post-nuclear future, the descendant of an...",True,True,False,False,False,False,False,True,False
1062,1060,Fallout: The Frontier,https://www.imdb.com/title/tt7471838/?ref_=adv...,2021.0,NaN,4.1,24.0,The ongoing conflict between the Legion and th...,True,True,False,False,False,False,False,True,False
1233,1231,Fallout Tactics: Brotherhood of Steel,https://www.imdb.com/title/tt0246614/?ref_=adv...,2001.0,M,7.4,784.0,"The Brotherhood of Steel, a faction of technol...",True,True,False,False,False,False,False,True,False
1872,1870,Fallout: New Vegas - Honest Hearts,https://www.imdb.com/title/tt13259848/?ref_=ad...,2011.0,M,7.5,74.0,The story leads the protagonist to the Canyon ...,True,True,False,False,False,False,False,True,False
1964,1962,Fallout 4: New Vegas,https://www.imdb.com/title/tt9054854/?ref_=adv...,2019.0,NaN,6.2,15.0,An unofficial fan-made recreation of Fallout: ...,True,True,False,False,False,False,False,True,False
2003,2001,Fallout: Brotherhood of Steel,https://www.imdb.com/title/tt0426456/?ref_=adv...,2004.0,NaN,5.5,111.0,The adventures of an initiate in the Brotherho...,True,True,False,False,False,False,False,True,False
2117,2115,Fallout: New Vegas - Old World Blues,https://www.imdb.com/title/tt13627658/?ref_=ad...,2011.0,NaN,8.3,77.0,After being transported to the Big MT research...,True,True,False,False,False,False,False,True,False
2170,2168,Fallout Legacy Collection,https://www.imdb.com/title/tt13409472/?ref_=ad...,2019.0,NaN,5.8,6.0,Add a Plot,True,False,False,False,False,False,False,False,False
2362,2360,Fallout: New Vegas - Simply Uncut,https://www.imdb.com/title/tt15448278/?ref_=ad...,2019.0,NaN,NaN,NaN,"Many NPCs, areas, items, quests, and concepts ...",True,False,False,False,False,False,False,False,False
2472,2470,Fallout 4: Far Harbor,https://www.imdb.com/title/tt13877574/?ref_=ad...,2016.0,NaN,8.0,69.0,A new case from Valentine's Detective Agency l...,True,True,False,False,False,False,False,True,False
2549,2547,Fallout: New Vegas - Dead Money,https://www.imdb.com/title/tt13129016/?ref_=ad...,2010.0,NaN,7.3,72.0,"You, the courier, were drawn to an abandoned B...",True,True,False,False,False,False,False,False,False
2681,2679,Fallout: Miami,https://www.imdb.com/title/tt9243702/?ref_=adv...,2019.0,NaN,NaN,NaN,Journey to the post-nuclear vacation wasteland...,True,True,False,False,False,False,False,True,False
2718,2716,Fallout 4: Fusion City Rising,https://www.imdb.com/title/tt6108962/?ref_=adv...,2016.0,NaN,7.9,12.0,Join Peter on a wild adventure to stop religio...,True,True,False,False,False,False,False,False,False
2861,2859,Fallout: New California,https://www.imdb.com/title/tt9162260/?ref_=adv...,2018.0,NaN,6.4,7.0,An all new story around an adopted resident of...,True,True,False,False,False,False,False,True,False
3047,3045,Fallout: New Vegas - Lonesome Road,https://www.imdb.com/title/tt13627682/?ref_=ad...,2011.0,NaN,7.7,60.0,Add a Plot,True,True,False,False,False,False,False,True,False
3086,3084,Fallout 4: Heather Casdin,https://www.imdb.com/title/tt16604526/?ref_=ad...,2017.0,NaN,NaN,NaN,A unique companion mod for Fallout 4 which add...,True,True,False,False,False,False,False,False,False
3127,3125,Fallout 3: Point Lookout,https://www.imdb.com/title/tt12702412/?ref_=ad...,2009.0,NaN,8.0,70.0,Point Lookout is the fourth downloadable expan...,True,True,False,False,False,False,False,False,False
3141,3139,Fallout 3: Operation: Anchorage,https://www.imdb.com/title/tt12702392/?ref_=ad...,2009.0,NaN,6.7,73.0,This expansion adds four to five hours of war-...,True,True,False,False,False,False,False,True,False
3165,3163,Fallout 4: Nuka-World,https://www.imdb.com/title/tt15378570/?ref_=ad...,2016.0,M,6.5,45.0,"Take a trip to Nuka-World, a vast amusement pa...",True,True,False,False,False,False,False,True,False
3206,3204,Fallout 3: Broken Steel,https://www.imdb.com/title/tt1925430/?ref_=adv...,2009.0,NaN,7.7,334.0,Expansion pack for Fallout 3 (2008). After Pro...,True,True,False,False,False,False,False,True,False
3440,3438,Fallout 76: Steel Reign,https://www.imdb.com/title/tt14987880/?ref_=ad...,2021.0,NaN,5.0,11.0,Add a Plot,True,True,False,False,False,False,False,True,False
3554,3552,Fallout 3: The Pitt,https://www.imdb.com/title/tt12702402/?ref_=ad...,2009.0,NaN,7.6,70.0,The fifth and final downloadable expansion for...,True,True,False,False,False,False,False,True,False
3615,3613,Fallout 3: Mothership Zeta,https://www.imdb.com/title/tt12702432/?ref_=ad...,2009.0,NaN,6.4,72.0,The fifth and final downloadable expansion for...,True,True,False,False,False,False,False,True,False
3719,3717,Fallout 76: Steel Dawn,https://www.imdb.com/title/tt13534124/?ref_=ad...,2020.0,NaN,6.4,28.0,Add a Plot,True,True,False,False,False,False,False,True,False
3731,3729,Fallout 76: Expeditions - The Pitt,https://www.imdb.com/title/tt21040946/?ref_=ad...,2022.0,NaN,NaN,NaN,Add a Plot,True,False,False,False,False,False,False,False,False
4012,4010,Fallout 4: Capital Wasteland,https://www.imdb.com/title/tt9543158/?ref_=adv...,NaN,NaN,NaN,NaN,Add a Plot,True,True,False,False,False,False,False,True,False
4190,4188,Fallout 76: Wastelanders,https://www.imdb.com/title/tt13871682/?ref_=ad...,2020.0,NaN,5.8,32.0,Add a Plot,True,True,False,False,False,False,False,True,False
5306,5304,Fallout 4: Automatron,https://www.imdb.com/title/tt15231134/?ref_=ad...,2016.0,M,6.4,30.0,The mysterious Mechanist has unleashed a horde...,True,True,False,False,False,False,False,True,False
8315,8313,Fallout 4 - Point Lookout,https://www.imdb.com/title/tt20242232/?ref_=ad...,2022.0,NaN,NaN,NaN,Add a Plot,True,False,False,False,False,False,False,False,False
9821,9819,Fallout: Cascadia,https://www.imdb.com/title/tt9203196/?ref_=adv...,2019.0,NaN,NaN,NaN,A full-size mod for Fallout 4 set in a post-nu...,True,True,False,False,False,False,False,True,False
10013,10011,Fallout 4,https://www.imdb.com/title/tt4741306/?ref_=adv...,2015.0,M,8.6,12791.0,"In the post-apocalyptic Boston, Massachusetts ...",True,True,False,False,False,False,False,True,False
10027,10025,Fallout 3,https://www.imdb.com/title/tt1073664/?ref_=adv...,2008.0,M,9.1,18905.0,"Centuries following nuclear war, a teen leaves...",True,True,False,False,False,False,False,True,False
10716,10714,Fallout 4: London,https://www.imdb.com/title/tt17074640/?ref_=ad...,2023.0,NaN,NaN,NaN,Add a Plot,False,True,False,False,False,False,False,False,False
12535,12533,Fallout 4: Wasteland Workshop,https://www.imdb.com/title/tt15378788/?ref_=ad...,2016.0,M,4.2,9.0,Add a Plot,False,True,False,False,False,False,False,True,False
13598,13596,Fallout 4: Vault-Tec Workshop,https://www.imdb.com/title/tt15231138/?ref_=ad...,2016.0,M,5.5,11.0,Add a Plot,False,True,False,False,False,False,False,True,False
14919,14917,Fallout 4: Contraptions Workshop,https://www.imdb.com/title/tt15378806/?ref_=ad...,2016.0,M,5.2,10.0,Add a Plot,False,True,False,False,False,False,False,True,False
19373,19371,Fallout: A Post-Nuclear Role-Playing Game,https://www.imdb.com/title/tt0134648/?ref_=adv...,1997.0,M,9.2,3773.0,After being sent by the overseer of his vault ...,True,True,False,False,False,False,False,True,False
19425,19423,Fallout New Vegas: Brave New World,https://www.imdb.com/title/tt12819644/?ref_=ad...,2020.0,NaN,5.6,5.0,Brave New World is a project that gathers the ...,False,False,False,False,False,False,False,True,False
19513,19511,Fallout Shelter,https://www.imdb.com/title/tt5430868/?ref_=adv...,2015.0,NaN,6.2,630.0,"As Overseer, you must expand and maintain your...",False,False,False,False,False,False,False,True,False

#### 4. What is the most common certificate for Sci-Fi games?

In [17]:
# only wanna show true (because that means they are under Sci-Fi games)
df.groupby('Sci_Fi')['certificate'].agg(pd.Series.mode)
# gave most common certificate for Sci-Fi games and games that aren't Sci-Fi

Sci_Fi
False    T
True     T
Name: certificate, dtype: object

#### 5. What percent of Thiller games have M or AO certificate?

In [28]:
# narrow down to thriller games
# then narrow down to just games that have M or AO certficate
# then find the percentage of Thriller games with it

thriller_m_ao = df[(df.Thriller==True) & (df.certificate=='M') | (df.certificate=='AO')]
print("Number of Thrillers with M or AO:", len(thriller_m_ao))

thriller = df[(df.Thriller==True)]
print("Total number of Thrillers:", len(thriller))

len(thriller_m_ao) / len(thriller)

Number of Thrillers with M or AO: 200
Total number of Thrillers: 523

0.3824091778202677

#### 6. What is the mean and median rating for Family games? for Action games?

Family

In [ ]:
df.groupby('Family').rating.agg(['mean','median'])

            mean  median
Family
False   7.104427     7.3
True    6.686450     6.9

Action

In [ ]:
df.groupby('Action').rating.agg(['mean','median'])

            mean  median
Action
False   6.998812     7.2
True    7.069257     7.2

#### 7. Which game from 2018 got the most votes?

In [ ]:
#df.groupby('year').votes.max()
#mask = df.year == 2018
#mask
#df[mask].votes.max()
df_year = df[(df.year == 2018)]
df_year[["name", "votes"]].max()

name     Zootopia: Dreaming People
votes                      35709.0
dtype: object

#### 8. What is the average rating for each genre (Action, Adventure, Comedy, Crime, Family, Fantasy, Mystery, Sci-Fi, and Thriller)?

In [82]:
genres = ["Action","Adventure","Sci_Fi","Thriller","Comedy","Family","Crime","Fantasy","Mystery"]

for genre in genres:
    print(f'{genre} rating mean:',(df[df[genre]].rating.mean()))

Action rating mean: 7.069257468699611
Adventure rating mean: 7.2494638480392135
Sci_Fi rating mean: 6.9492544492544575
Thriller rating mean: 7.1071428571428585
Comedy rating mean: 7.189196197061372
Family rating mean: 6.686450381679379
Crime rating mean: 7.315111111111107
Fantasy rating mean: 7.261732229123556
Mystery rating mean: 7.4513286713286675

#### 9. Which year's games received the most votes?

In [ ]:
df.groupby('year')[['votes']].max().sort_values(['votes'], ascending=False)
#df_game = df.groupby('year').votes.max()
#df_game

          votes
year
2013.0  60597.0
2004.0  39632.0
2018.0  35709.0
2008.0  34555.0
2011.0  30766.0
...         ...
1964.0      NaN
2023.0      NaN
2024.0      NaN
2025.0      NaN
2027.0      NaN

[61 rows x 1 columns]

#### 10. What's the average number of votes for games that are not Action games?

In [20]:
#df.groupby(['Adventure','Comedy','Crime','Family','Fantasy','Mystery','Sci_Fi','Thriller']).votes.mean()
df.groupby('Action').votes.agg(['mean'])

              mean
Action
False   188.427157
True    824.919797

#### 11. What games are platformers?

In [ ]:
games = df[df.plot_summary.str.contains("platformers")]
games

,Unnamed: 0,name,url,year,certificate,rating,votes,plot_summary,Action,Adventure,Comedy,Crime,Family,Fantasy,Mystery,Sci_Fi,Thriller
8927,8925,Oniken,https://www.imdb.com/title/tt18115072/?ref_=ad...,2012.0,T,NaN,NaN,In a post-apocalyptic future controlled by a s...,True,True,False,False,False,False,False,True,False
9545,9543,Rise & Shine,https://www.imdb.com/title/tt11494552/?ref_=ad...,2017.0,M,6.8,5.0,"Rise and Shine is a true ""think and gun"" that ...",True,False,False,False,False,False,False,False,False
13314,13312,Mutant Mudds,https://www.imdb.com/title/tt17158468/?ref_=ad...,2012.0,E,NaN,NaN,Love pixels and platformers? Is there a specia...,True,True,False,False,False,True,False,False,False
13530,13528,Land of Illusion,https://www.imdb.com/title/tt0462394/?ref_=adv...,1993.0,Not Rated,7.3,46.0,The third entry in Mickey Mouse's 'Illusion' s...,False,True,False,False,False,True,False,False,False

#### 12. What is the most common certificate of games with ratings greater than 8.0 and votes greater than 1000?

In [72]:
# section it to games with ratings greater than 8.0 and votes greater than 1000
    # do i need to use mode to find the most common
#df.groupby('Sci_Fi')['certificate'].agg(pd.Series.mode)
common_certificate = df[(df.rating > 8.0) & (df.votes > 1000)]
common_certificate.certificate.value_counts()

M            363
T            180
E            102
E10+          51
K-A           13
AO             1
Unrated        1
Not Rated      1
Name: certificate, dtype: int64

#### 13. For games with ratings greater than the 75th percentile for ratings and a number of votes greater than the 75th percentile for votes, what is the most common genre?

In [57]:
# saving as a variable because you want to use it later
# takeaway (how to frame the question)
rating_threshold = df.rating.quantile(0.75)
votes_threshold = df.votes.quantile(0.75)

genres = ["Action","Adventure","Sci_Fi","Thriller","Comedy","Family","Crime","Fantasy","Mystery"]

# this shortens everything so you don't have to keep writing out the same two 
good_games = df[(df.rating > rating_threshold) & (df.votes > votes_threshold)]
for genre in genres:
    print(genre, len(good_games[good_games[genre]==True] ))


#good_action_games = good_games[good_games.Action==True]
#print("Action", len(good_action_games))

#good_adventure_games = good_games[good_games.Adventure==True]
#len(good_adventure_games)

Action 1102
Adventure 993
Sci_Fi 186
Thriller 55
Comedy 151
Family 113
Crime 150
Fantasy 443
Mystery 121

#### 14. What are the average ratings by year?

In [59]:
# first section by year and then find the average rating for each year
# can convert a series into a dataframe
pd.DataFrame(df.groupby("year").rating.mean())

          rating
year
1952.0  7.000000
1962.0  6.800000
1964.0       NaN
1969.0  6.950000
1970.0  4.300000
...          ...
2022.0  7.563063
2023.0       NaN
2024.0       NaN
2025.0       NaN
2027.0       NaN

[61 rows x 1 columns]

#### 15. For each certificate, what was the average rating and average number of votes?

In [65]:
# first group by certificate
certificate_votes = df.groupby('certificate')[['votes','rating']].mean()
print(certificate_votes)

                   votes    rating
certificate
12             31.375000  7.350000
AO            246.333333  6.493333
Approved       52.333333  6.900000
CE             12.600000  5.520000
E             332.329063  7.085637
E10+          520.265766  7.181231
EC             18.857143  6.142857
G              11.500000  5.600000
GA            165.105263  6.531579
K-A           349.324607  6.913089
M            2498.627557  7.515584
MA-13          83.200000  7.080000
MA-17         165.666667  6.000000
Not Rated     110.759124  6.703650
PG            106.333333  5.933333
PG-13         119.000000  6.628571
Passed         19.000000  4.700000
T             829.020862  7.295178
TV-14         127.000000  7.000000
TV-MA           8.000000  7.000000
Unrated       135.973333  6.478222